# Generated by Django 5.2 on 2025-04-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversation_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='session_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
