# Generated by Django 5.2 on 2025-10-25 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_conversation_session_id_conversation_is_demo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='current_word',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='guesses_remaining',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='conversation',
            name='num_rounds',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('related_words', models.JSONField(default=list)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='api.topic'),
        ),
    ]
